<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bpmn" nsURI="http://www.example.org/bpmn" nsPrefix="bpmn">
  <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="#//Artifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation" eSuperTypes="#//Artifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataObject" eSuperTypes="#//Artifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact" eSuperTypes="#//GraphicalObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="articaftTypes" eType="ecore:EDataType http://www.eclipse.org/sirius/1.1.0#//description/TypeName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Swinlane" eSuperTypes="#//GraphicalObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphicalObject" instanceTypeName="a">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectingObject" eSuperTypes="#//GraphicalObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pool" eSuperTypes="#//Swinlane"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lane" eSuperTypes="#//Swinlane"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceFlow" eSuperTypes="#//ConnectingObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionExpression" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conditionType" eType="ecore:EDataType http://www.eclipse.org/sirius/1.1.0#//description/TypeName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlowObject" eSuperTypes="#//GraphicalObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//FlowObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//SequenceFlow.1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activityType" eType="ecore:EDataType http://www.eclipse.org/sirius/1.1.0#//description/TypeName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//FlowObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventType" eType="ecore:EDataType http://www.eclipse.org/sirius/1.1.0#//description/TypeName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gateway" eSuperTypes="#//FlowObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="StartEvent" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntermediateEvent" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="EndEvent" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceFlow"/>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//Activity"/>
  <eClassifiers xsi:type="ecore:EClass" name="SendTask" eSuperTypes="#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReceiveTask" eSuperTypes="#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessRuleTask" eSuperTypes="#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubProcess" eSuperTypes="#//Activity"/>
  <eClassifiers xsi:type="ecore:EClass" name="ManualTask" eSuperTypes="#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="UserTask" eSuperTypes="#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceTask" eSuperTypes="#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScriptTask" eSuperTypes="#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExclusiveGateway" eSuperTypes="#//Gateway">
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//SequenceFlow.4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InclusiveGateway" eSuperTypes="#//Gateway">
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//SequenceFlow.3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParalelGateway" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexGateway" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceFlow"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceFlow"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceFlow"/>
</ecore:EPackage>
